name: Enviar e-mail todo dia - 12h

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  enviar_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Instalar dependências
      run: pip install schedule

    - name: Enviar E-mail
      run: python .github/workflows/enviar_email.py
